const resList = [
  {
    id: 1,
    restaurant_name: "Meghana Foods",
    cuisine: ["Biryani", "North Indian", "Asian"],
    ratings: 3.8,
    delivery_time: "38 Minutes",
    cost_for_two: 500,
    location: {
      address: "Koramangala, Bangalore",
      city: "Bangalore",
      area: "Koramangala",
    },
    offers: ["20% off on orders above ₹300"],
    contact_number: "+91 9876543210",
    cloudinaryImageId: "meghana_foods_img",
  },
  {
    id: 2,
    restaurant_name: "Empire Restaurant",
    cuisine: ["South Indian", "North Indian", "Arabian"],
    ratings: 3.9,
    delivery_time: "30 Minutes",
    cost_for_two: 450,
    location: {
      address: "Indiranagar, Bangalore",
      city: "Bangalore",
      area: "Indiranagar",
    },
    offers: ["10% cashback on all orders"],
    contact_number: "+91 8765432109",
    cloudinaryImageId: "empire_restaurant_img",
  },
  {
    id: 3,
    restaurant_name: "Truffles",
    cuisine: ["Italian", "Continental", "American"],
    ratings: 4.7,
    delivery_time: "45 Minutes",
    cost_for_two: 700,
    location: {
      address: "HSR Layout, Bangalore",
      city: "Bangalore",
      area: "HSR Layout",
    },
    offers: ["Buy 1 Get 1 Free on Burgers"],
    contact_number: "+91 7654321098",
    cloudinaryImageId: "truffles_img",
  },
  {
    id: 4,
    restaurant_name: "Sagar Ratna",
    cuisine: ["South Indian", "North Indian"],
    ratings: 3.6,
    delivery_time: "25 Minutes",
    cost_for_two: 300,
    location: {
      address: "Jayanagar, Bangalore",
      city: "Bangalore",
      area: "Jayanagar",
    },
    offers: ["Free delivery on orders above ₹200"],
    contact_number: "+91 6543210987",
    cloudinaryImageId: "sagar_ratna_img",
  },
  {
    id: 5,
    restaurant_name: "Punjabi By Nature",
    cuisine: ["Punjabi", "North Indian", "Tandoori"],
    ratings: 4.5,
    delivery_time: "35 Minutes",
    cost_for_two: 600,
    location: {
      address: "Whitefield, Bangalore",
      city: "Bangalore",
      area: "Whitefield",
    },
    offers: ["15% off on first order"],
    contact_number: "+91 6543212345",
    cloudinaryImageId: "punjabi_by_nature_img",
  },
  {
    id: 6,
    restaurant_name: "Beijing Bites",
    cuisine: ["Chinese", "Thai"],
    ratings: 4.0,
    delivery_time: "40 Minutes",
    cost_for_two: 550,
    location: {
      address: "Marathahalli, Bangalore",
      city: "Bangalore",
      area: "Marathahalli",
    },
    offers: ["Flat ₹100 off on orders above ₹500"],
    contact_number: "+91 6543213456",
    cloudinaryImageId: "beijing_bites_img",
  },
  {
    id: 7,
    restaurant_name: "Barbeque Nation",
    cuisine: ["Barbecue", "Grill", "Continental"],
    ratings: 4.2,
    delivery_time: "50 Minutes",
    cost_for_two: 1000,
    location: {
      address: "Electronic City, Bangalore",
      city: "Bangalore",
      area: "Electronic City",
    },
    offers: ["Free dessert with every meal"],
    contact_number: "+91 6543214567",
    cloudinaryImageId: "barbeque_nation_img",
  },
  {
    id: 8,
    restaurant_name: "Paradise Biryani",
    cuisine: ["Biryani", "North Indian"],
    ratings: 3.4,
    delivery_time: "30 Minutes",
    cost_for_two: 450,
    location: {
      address: "BTM Layout, Bangalore",
      city: "Bangalore",
      area: "BTM Layout",
    },
    offers: ["20% off on all orders"],
    contact_number: "+91 6543215678",
    cloudinaryImageId: "paradise_biryani_img",
  },
  {
    id: 9,
    restaurant_name: "The Bowl Company",
    cuisine: ["Continental", "Asian"],
    ratings: 4.8,
    delivery_time: "20 Minutes",
    cost_for_two: 400,
    location: {
      address: "Domlur, Bangalore",
      city: "Bangalore",
      area: "Domlur",
    },
    offers: ["Free delivery for first 3 orders"],
    contact_number: "+91 6543216789",
    cloudinaryImageId: "the_bowl_company_img",
  },
  {
    id: 10,
    restaurant_name: "Corner House",
    cuisine: ["Desserts", "Ice Cream"],
    ratings: 3.9,
    delivery_time: "15 Minutes",
    cost_for_two: 200,
    location: {
      address: "Indiranagar, Bangalore",
      city: "Bangalore",
      area: "Indiranagar",
    },
    offers: ["Buy 2 Get 1 Free on Ice Creams"],
    contact_number: "+91 6543217890",
    cloudinaryImageId: "corner_house_img",
  },
  {
    id: 11,
    restaurant_name: "Andhra Spice",
    cuisine: ["Andhra", "South Indian"],
    ratings: 4.1,
    delivery_time: "25 Minutes",
    cost_for_two: 350,
    location: {
      address: "HSR Layout, Bangalore",
      city: "Bangalore",
      area: "HSR Layout",
    },
    offers: ["10% cashback"],
    contact_number: "+91 6543218901",
    cloudinaryImageId: "andhra_spice_img",
  },
  {
    id: 12,
    restaurant_name: "Wow! Momo",
    cuisine: ["Tibetan", "Fast Food"],
    ratings: 3.7,
    delivery_time: "30 Minutes",
    cost_for_two: 250,
    location: {
      address: "Whitefield, Bangalore",
      city: "Bangalore",
      area: "Whitefield",
    },
    offers: ["Free drink on orders above ₹250"],
    contact_number: "+91 6543219012",
    cloudinaryImageId: "wow_momo_img",
  },
  {
    id: 13,
    restaurant_name: "Burger King",
    cuisine: ["Fast Food", "American"],
    ratings: 3.3,
    delivery_time: "20 Minutes",
    cost_for_two: 300,
    location: {
      address: "Marathahalli, Bangalore",
      city: "Bangalore",
      area: "Marathahalli",
    },
    offers: ["Flat 20% off on combos"],
    contact_number: "+91 6543220123",
    cloudinaryImageId: "burger_king_img",
  },
  {
    id: 14,
    restaurant_name: "KFC",
    cuisine: ["Fast Food", "American"],
    ratings: 4.3,
    delivery_time: "25 Minutes",
    cost_for_two: 350,
    location: {
      address: "Koramangala, Bangalore",
      city: "Bangalore",
      area: "Koramangala",
    },
    offers: ["Free fries on orders above ₹300"],
    contact_number: "+91 6543221234",
    cloudinaryImageId: "kfc_img",
  },
  {
    id: 15,
    restaurant_name: "A2B - Adyar Ananda Bhavan",
    cuisine: ["South Indian", "Indian Sweets"],
    ratings: 3.6,
    delivery_time: "20 Minutes",
    cost_for_two: 300,
    location: {
      address: "Jayanagar, Bangalore",
      city: "Bangalore",
      area: "Jayanagar",
    },
    offers: ["10% off on all sweets"],
    contact_number: "+91 6543222345",
    cloudinaryImageId: "a2b_img",
  },
  {
    id: 16,
    restaurant_name: "Taco Bell",
    cuisine: ["Mexican", "Fast Food"],
    ratings: 4.1,
    delivery_time: "20 Minutes",
    cost_for_two: 300,
    location: {
      address: "Domlur, Bangalore",
      city: "Bangalore",
      area: "Domlur",
    },
    offers: ["Buy 1 Get 1 Free on Tacos"],
    contact_number: "+91 6543223456",
    cloudinaryImageId: "taco_bell_img",
  },
  {
    id: 17,
    restaurant_name: "Chai Point",
    cuisine: ["Beverages", "Snacks"],
    ratings: 3.9,
    delivery_time: "15 Minutes",
    cost_for_two: 200,
    location: {
      address: "Indiranagar, Bangalore",
      city: "Bangalore",
      area: "Indiranagar",
    },
    offers: ["Free cookie with chai"],
    contact_number: "+91 6543224567",
    cloudinaryImageId: "chai_point_img",
  },
  {
    id: 18,
    restaurant_name: "Subway",
    cuisine: ["Healthy Food", "Sandwiches"],
    ratings: 3.7,
    delivery_time: "15 Minutes",
    cost_for_two: 300,
    location: {
      address: "Whitefield, Bangalore",
      city: "Bangalore",
      area: "Whitefield",
    },
    offers: ["15% off on orders above ₹250"],
    contact_number: "+91 6543225678",
    cloudinaryImageId: "subway_img",
  },
  {
    id: 19,
    restaurant_name: "Domino's Pizza",
    cuisine: ["Italian", "Fast Food"],
    ratings: 3.5,
    delivery_time: "30 Minutes",
    cost_for_two: 400,
    location: {
      address: "Marathahalli, Bangalore",
      city: "Bangalore",
      area: "Marathahalli",
    },
    offers: ["₹100 off on first online order"],
    contact_number: "+91 6543226789",
    cloudinaryImageId: "dominos_pizza_img",
  },
  {
    id: 20,
    restaurant_name: "Pizza Hut",
    cuisine: ["Italian", "Fast Food"],
    ratings: 4.0,
    delivery_time: "25 Minutes",
    cost_for_two: 450,
    location: {
      address: "Electronic City, Bangalore",
      city: "Bangalore",
      area: "Electronic City",
    },
    offers: ["Buy 1 Get 1 on medium pizzas"],
    contact_number: "+91 6543227890",
    cloudinaryImageId: "pizza_hut_img",
  },
];


export default resList;
